flowchart LR
    User[{{USER_GROUP}}] --> App[{{PRODUCT_NAME}}]
    App --> Data[{{PRIMARY_DATA_STORE}}]
    App --> Ext[{{EXTERNAL_SERVICE}}]
    Ops[Operations team] --> App
    Gov[Governance board] --> App
